development:
  adapter: postgresql
  encoding: utf8
  database: coasthouse_development
  pool: 5
  username: vladiim
  password:
  host: localhost

test: &test
  adapter: postgresql
  encoding: utf8
  database: coasthouse_test
  pool: 5
  username: vladiim
  password:
  host: localhost
cucumber:
  <<: *test